[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/mshumayl/nvim.git"
    refreshPeriod = "168h"
[".config/nvim".clone]
    args = ["--depth", "1"]
[".config/nvim".pull]
    args = ["--ff-only"]
