[display]
default_width = "medium"
default_table_page_size = 10
dataframes = "rich"
theme = "light"
cell_output = "above"
code_editor_font_size = 14

[language_servers.pylsp]
enable_pyflakes = false
enable_mypy = true
enable_flake8 = false
enable_pylint = false
enable_ruff = true
enabled = true
enable_pydocstyle = false

[snippets]
custom_paths = []
include_default_snippets = true

[runtime]
auto_reload = "off"
watcher_on_save = "lazy"
output_max_bytes = 8000000
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
auto_instantiate = true
reactive_tests = true

[save]
autosave_delay = 1000
format_on_save = false
autosave = "after_delay"

[keymap]
preset = "vim"
[keymap.overrides]

[diagnostics]

[server]
follow_symlink = false
browser = "default"

[ai]
rules = ""

[completion]
copilot = false
activate_on_typing = true

[formatting]
line_length = 79

[package_management]
manager = "pip"

[experimental]
